spring:
  application:
    name: restapi
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:h2:file:./spring-boot-h2-db;DB_CLOSE_ON_EXIT=FALSE
    username: restapi
    password:
    driver-class-name: org.h2.Driver

